# NumPy

## Why NumPy

High level calculation

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [2]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a*b

array([ 2,  6, 12, 20])

## Creating NumPy Array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2,13]) # Only one type value

array([ 3.14,  4.  ,  2.  , 13.  ])

In [6]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [7]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [11]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.random.normal(10,4,(3,4)) # Mean 10 - Std 4

array([[ 9.27629909, 19.60408947,  9.74542585, 12.13035717],
       [10.5122264 ,  1.93775877,  8.03301157,  7.22055284],
       [13.60095442, 13.44944115,  9.9228697 ,  5.2160341 ]])

In [13]:
np.random.randint(0,10,(3,3)) # Random numbers between 0-10

array([[2, 8, 2],
       [7, 7, 8],
       [5, 5, 8]])

## Feature of NumPy

* **ndim**: _dimention number_
* **shape**: _dimention information_
* **size**: _total number of elements_
* dtype: type of array

In [14]:
a = np.random.randint(10, size = 10)
a

array([6, 0, 0, 6, 1, 0, 9, 7, 4, 3])

In [15]:
a.ndim

1

In [16]:
a.shape

(10,)

In [17]:
a.size

10

In [18]:
a.dtype

dtype('int64')

In [19]:
b = np.random.randint(10, size = (3,5))
b

array([[9, 6, 2, 2, 6],
       [2, 2, 4, 4, 4],
       [6, 4, 8, 2, 5]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3, 5)

In [22]:
b.size

15

In [23]:
b.dtype

dtype('int64')

## Reshaping

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a = np.arange(1,10) # vector
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a.ndim

1

In [28]:
b = a.reshape((1,9)) # matrix
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
b.ndim

2

## Concatenation

In [30]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [31]:
z = np.array([7,8,9])

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 2D

a = np.array([[1,2,3],
              [4,5,6]])

np.concatenate([a,a]) # axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting

In [34]:
x = np.array([1,2,3,99,99,3,2,1])

np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [35]:
a,b,c = np.split(x, [3,5])

In [36]:
a

array([1, 2, 3])

In [37]:
b

array([99, 99])

In [38]:
c

array([3, 2, 1])

In [39]:
# 2D

m = np.arange(16).reshape(4,4)

m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [41]:
k,l = np.vsplit(m,[2])

In [42]:
k

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
l

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [46]:
r,t = np.hsplit(m,[2])

In [47]:
r

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [48]:
t

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sorting

In [49]:
v = np.array([2,1,4,3,5])

v

array([2, 1, 4, 3, 5])

In [50]:
np.sort(v) # do not change original v

array([1, 2, 3, 4, 5])

In [51]:
v.sort() # change original v

v

array([1, 2, 3, 4, 5])

In [52]:
# 2D

m = np.random.normal(20,5,(3,3))

In [53]:
m

array([[21.24504635, 25.08472684, 17.98607396],
       [24.79004753, 19.52396118, 21.30882086],
       [16.57892303, 24.78823093, 18.43029769]])

In [54]:
np.sort(m, axis = 1)

array([[17.98607396, 21.24504635, 25.08472684],
       [19.52396118, 21.30882086, 24.79004753],
       [16.57892303, 18.43029769, 24.78823093]])

In [55]:
np.sort(m, axis = 0)

array([[16.57892303, 19.52396118, 17.98607396],
       [21.24504635, 24.78823093, 18.43029769],
       [24.79004753, 25.08472684, 21.30882086]])

## Reaching elements with index

In [56]:
a = np.random.randint(10, size = 10)

a

array([0, 0, 1, 6, 1, 3, 0, 5, 1, 8])

In [57]:
a[0]

0

In [58]:
a[-1]

8

In [59]:
a[0] = 100

a

array([100,   0,   1,   6,   1,   3,   0,   5,   1,   8])

In [60]:
# 2D

m = np.random.randint(10, size = (3,5))

m

array([[4, 3, 4, 4, 1],
       [8, 4, 8, 8, 1],
       [1, 4, 6, 4, 0]])

In [61]:
m[0,0]

4

In [62]:
m[1,1]

4

In [63]:
m[1,4]

1

In [64]:
m[1,4] = 99

In [65]:
m

array([[ 4,  3,  4,  4,  1],
       [ 8,  4,  8,  8, 99],
       [ 1,  4,  6,  4,  0]])

In [66]:
m[1,4] = 2.2

In [67]:
m

array([[4, 3, 4, 4, 1],
       [8, 4, 8, 8, 2],
       [1, 4, 6, 4, 0]])

## Slicing

In [68]:
a = np.arange(20,30)

a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
a[0:3]

array([20, 21, 22])

In [70]:
a[:4]

array([20, 21, 22, 23])

In [71]:
a[2:]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
a[1::2]

array([21, 23, 25, 27, 29])

In [73]:
a[::2]

array([20, 22, 24, 26, 28])

In [74]:
a[0::3]

array([20, 23, 26, 29])

In [75]:
# 2D

m = np.random.randint(10, size = (5,5))

m

array([[9, 7, 9, 8, 2],
       [7, 5, 4, 5, 5],
       [3, 3, 2, 0, 5],
       [9, 3, 8, 7, 2],
       [1, 1, 0, 6, 7]])

In [76]:
m[:,0]

array([9, 7, 3, 9, 1])

In [77]:
m[:,1]

array([7, 5, 3, 3, 1])

In [78]:
m[:,4]

array([2, 5, 5, 2, 7])

In [79]:
m[0,:]

array([9, 7, 9, 8, 2])

In [80]:
m[1,:]

array([7, 5, 4, 5, 5])

In [81]:
m[0:2, 0:3]

array([[9, 7, 9],
       [7, 5, 4]])

In [82]:
m[:,0:2]

array([[9, 7],
       [7, 5],
       [3, 3],
       [9, 3],
       [1, 1]])

In [83]:
m[1:3,0:2]

array([[7, 5],
       [3, 3]])

In [84]:
# Continue

In [85]:
a = np.random.randint(10, size = (5,5))

a

array([[3, 8, 3, 9, 8],
       [1, 0, 7, 3, 9],
       [3, 0, 9, 7, 0],
       [9, 8, 2, 7, 8],
       [4, 0, 8, 2, 8]])

In [86]:
alt_a = a[0:3,0:2]

alt_a

array([[3, 8],
       [1, 0],
       [3, 0]])

In [87]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

alt_a

array([[9999,    8],
       [   1,  888],
       [   3,    0]])

In [88]:
a

array([[9999,    8,    3,    9,    8],
       [   1,  888,    7,    3,    9],
       [   3,    0,    9,    7,    0],
       [   9,    8,    2,    7,    8],
       [   4,    0,    8,    2,    8]])

In [89]:
m = np.random.randint(10, size = (5,5))

m

array([[4, 9, 0, 6, 4],
       [4, 4, 5, 6, 9],
       [5, 3, 3, 7, 7],
       [3, 8, 3, 4, 6],
       [6, 7, 8, 3, 2]])

In [90]:
alt_b = m[0:3, 0:2].copy()

alt_b

array([[4, 9],
       [4, 4],
       [5, 3]])

In [91]:
alt_b[0,0] = 9999

alt_b

array([[9999,    9],
       [   4,    4],
       [   5,    3]])

In [92]:
m

array([[4, 9, 0, 6, 4],
       [4, 4, 5, 6, 9],
       [5, 3, 3, 7, 7],
       [3, 8, 3, 4, 6],
       [6, 7, 8, 3, 2]])

## Fancy Index

In [93]:
v = np.arange(0,30,3)

v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [94]:
v[1]

3

In [95]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [96]:
al_getir = [1,3,5]

v[al_getir] # fancy index

array([ 3,  9, 15])

In [97]:
# 2D

m = np.arange(9).reshape((3,3))

m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
satir = np.array([0,1])
sutun = np.array([1,2])

m[satir,sutun]

array([1, 5])

In [99]:
# basit index ile fancy index

In [100]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
m[0,[1,2]]

array([1, 2])

In [102]:
# slice ile fancy

m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu eleman işlemleri

In [103]:
v = np.array([1,2,3,4,5])

v < 3

array([ True,  True, False, False, False])

In [104]:
v[v < 3]

array([1, 2])

In [105]:
v[v >= 3]

array([3, 4, 5])

In [106]:
v*2

array([ 2,  4,  6,  8, 10])

In [107]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [108]:
v**2

array([ 1,  4,  9, 16, 25])

## Matematiksel İşlemler

In [109]:
v = np.array([1,2,3,4,5])

v

array([1, 2, 3, 4, 5])

In [110]:
# ufunc

In [111]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [112]:
np.add(v,2)

array([3, 4, 5, 6, 7])

In [113]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [114]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [115]:
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [116]:
np.mod(v,2) # %

array([1, 0, 1, 0, 1])

In [117]:
np.absolute(np.array([-3]))

array([3])

In [118]:
np.sin(360)

0.9589157234143065

In [119]:
np.cos(180)

-0.5984600690578581

In [120]:
v = np.array([1,2,3])

np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [121]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

## NumPy ile İki Bilinmeyenli denklem

5*x0 + x1 = 12

x0 + 3*x1 =10

In [122]:
import numpy as np

a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [123]:
a

array([[5, 1],
       [1, 3]])

In [124]:
b

array([12, 10])

In [125]:
x = np.linalg.solve(a,b)

x

array([1.85714286, 2.71428571])